import type { FenrirNode, FenrirEdge } from '@/types'
import { riskColor } from './riskScoring'
import { defangAll } from './defang'

export async function exportMarkdown(
  nodes: FenrirNode[],
  edges: FenrirEdge[],
  enrichmentResults: Record<string, unknown[]>
): Promise<string> {
  const date = new Date().toISOString().split('T')[0]
  const highRisk = nodes.filter(n => n.riskScore >= 60)
  const medRisk = nodes.filter(n => n.riskScore >= 30 && n.riskScore < 60)
  const clean = nodes.filter(n => n.riskScore < 30 && n.enriched)

  let md = `# Fenrir Threat Intelligence Report
> Generated: ${new Date().toLocaleString()} | Total IOCs: ${nodes.length}

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Total Indicators | ${nodes.length} |
| High Risk (≥60) | ${highRisk.length} |
| Medium Risk (30-59) | ${medRisk.length} |
| Clean (<30) | ${clean.length} |
| Relationships | ${edges.length} |

`

  if (highRisk.length > 0) {
    md += `## 🔴 High Risk Indicators\n\n`
    highRisk.forEach(n => {
      md += `### \`${defangAll(n.label)}\`\n`
      md += `- **Type:** ${n.indicatorType ?? n.type}\n`
      md += `- **Risk Score:** ${n.riskScore}/100 (${n.riskLevel.toUpperCase()})\n`
      md += `- **Confidence:** ${Math.round(n.confidence * 100)}%\n`
      const results = (enrichmentResults[n.id] ?? []) as { provider: string; riskScore: number; tags: string[]; error?: string }[]
      if (results.length > 0) {
        md += `- **Sources:**\n`
        results.forEach(r => {
          if (!r.error) md += `  - ${r.provider}: ${r.riskScore}/100${r.tags.length ? ` · ${r.tags.slice(0, 3).join(', ')}` : ''}\n`
        })
      }
      if (n.notes) md += `- **Notes:** ${n.notes}\n`
      md += '\n'
    })
  }

  if (medRisk.length > 0) {
    md += `## 🟡 Medium Risk Indicators\n\n`
    medRisk.forEach(n => {
      md += `- \`${defangAll(n.label)}\` — ${n.riskScore}/100 (${n.indicatorType ?? n.type})\n`
    })
    md += '\n'
  }

  if (clean.length > 0) {
    md += `## 🟢 Clean / Low Risk\n\n`
    clean.forEach(n => {
      md += `- \`${defangAll(n.label)}\` — ${n.riskScore}/100\n`
    })
    md += '\n'
  }

  if (edges.length > 0) {
    md += `## Relationship Map\n\n`
    edges.forEach(e => {
      const src = nodes.find(n => n.id === e.source)?.label ?? e.source
      const tgt = nodes.find(n => n.id === e.target)?.label ?? e.target
      md += `- \`${defangAll(src)}\` **${e.type.replace(/_/g, ' ')}** \`${defangAll(tgt)}\`\n`
    })
    md += '\n'
  }

  md += `## Raw IOC List (Defanged)\n\n\`\`\`\n`
  nodes.forEach(n => { md += `${defangAll(n.label)}\n` })
  md += `\`\`\`\n\n---\n*Generated by Fenrir | 0xprit3sh*\n`

  return md
}

export async function exportPDF(
  nodes: FenrirNode[],
  edges: FenrirEdge[],
  enrichmentResults: Record<string, unknown[]>
): Promise<void> {
  const md = await exportMarkdown(nodes, edges, enrichmentResults)

  // Build HTML for PDF rendering
  const highRisk = nodes.filter(n => n.riskScore >= 60)
  const medRisk  = nodes.filter(n => n.riskScore >= 30 && n.riskScore < 60)
  const clean    = nodes.filter(n => n.riskScore < 30 && n.enriched)

  const nodeRow = (n: FenrirNode) => `
    <tr>
      <td style="font-family:monospace;font-size:11px;word-break:break-all">${defangAll(n.label)}</td>
      <td>${n.indicatorType ?? n.type}</td>
      <td style="color:${riskColor(n.riskLevel)};font-weight:600">${n.riskScore}/100</td>
      <td style="text-transform:capitalize">${n.riskLevel}</td>
      <td style="font-size:10px">${
        ((enrichmentResults[n.id] ?? []) as { provider: string; tags: string[]; error?: string }[])
          .filter(r => !r.error)
          .map(r => r.provider)
          .join(', ')
      }</td>
    </tr>`

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Fenrir Report — ${new Date().toLocaleDateString()}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #0f172a; padding: 40px; font-size: 13px; line-height: 1.5; }
  h1 { font-size: 24px; font-weight: 700; color: #7c3aed; margin-bottom: 4px; }
  h2 { font-size: 15px; font-weight: 600; margin: 28px 0 10px; padding-bottom: 6px; border-bottom: 1.5px solid #e2e8f0; }
  .meta { color: #64748b; font-size: 12px; margin-bottom: 28px; }
  .summary { display: grid; grid-template-columns: repeat(4,1fr); gap: 12px; margin-bottom: 24px; }
  .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 14px; text-align: center; }
  .card .num { font-size: 28px; font-weight: 700; color: #7c3aed; }
  .card .lbl { font-size: 11px; color: #64748b; margin-top: 2px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th { background: #f1f5f9; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #475569; padding: 8px 10px; text-align: left; }
  td { padding: 8px 10px; border-bottom: 1px solid #f1f5f9; font-size: 12px; vertical-align: top; }
  tr:hover td { background: #f8fafc; }
  .badge { display:inline-block; padding:2px 7px; border-radius:999px; font-size:10px; font-weight:600; }
  .red  { background:#fef2f2; color:#ef4444; }
  .amber{ background:#fffbeb; color:#f59e0b; }
  .green{ background:#f0fdf4; color:#10b981; }
  .edge { font-size:11px; padding:4px 0; border-bottom:1px solid #f1f5f9; display:flex; gap:8px; align-items:center; }
  .edge code { font-family:monospace; background:#f1f5f9; padding:1px 5px; border-radius:4px; font-size:10px; word-break:break-all; }
  .rel-label { color:#7c3aed; font-size:10px; font-style:italic; flex-shrink:0; }
  .ioc-list { font-family:monospace; font-size:11px; background:#f8fafc; border:1px solid #e2e8f0; border-radius:8px; padding:14px; line-height:2; word-break:break-all; }
  .footer { margin-top:40px; padding-top:16px; border-top:1px solid #e2e8f0; color:#94a3b8; font-size:11px; text-align:center; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
<h1>⬡ Fenrir Threat Intelligence Report</h1>
<div class="meta">Generated: ${new Date().toLocaleString()} &nbsp;·&nbsp; 0xprit3sh</div>

<div class="summary">
  <div class="card"><div class="num">${nodes.length}</div><div class="lbl">Total IOCs</div></div>
  <div class="card"><div class="num" style="color:#ef4444">${highRisk.length}</div><div class="lbl">High Risk</div></div>
  <div class="card"><div class="num" style="color:#f59e0b">${medRisk.length}</div><div class="lbl">Medium Risk</div></div>
  <div class="card"><div class="num" style="color:#10b981">${clean.length}</div><div class="lbl">Clean</div></div>
</div>

${highRisk.length > 0 ? `
<h2>🔴 High Risk Indicators</h2>
<table>
  <tr><th>Indicator</th><th>Type</th><th>Score</th><th>Level</th><th>Sources</th></tr>
  ${highRisk.map(nodeRow).join('')}
</table>` : ''}

${medRisk.length > 0 ? `
<h2>🟡 Medium Risk Indicators</h2>
<table>
  <tr><th>Indicator</th><th>Type</th><th>Score</th><th>Level</th><th>Sources</th></tr>
  ${medRisk.map(nodeRow).join('')}
</table>` : ''}

${clean.length > 0 ? `
<h2>🟢 Low Risk / Clean</h2>
<table>
  <tr><th>Indicator</th><th>Type</th><th>Score</th><th>Level</th><th>Sources</th></tr>
  ${clean.map(nodeRow).join('')}
</table>` : ''}

${edges.length > 0 ? `
<h2>Relationship Map</h2>
<div style="margin-bottom:16px">
${edges.map(e => {
  const src = nodes.find(n => n.id === e.source)?.label ?? e.source
  const tgt = nodes.find(n => n.id === e.target)?.label ?? e.target
  return `<div class="edge"><code>${defangAll(src)}</code><span class="rel-label">${e.type.replace(/_/g,' ')}</span><code>${defangAll(tgt)}</code></div>`
}).join('')}
</div>` : ''}

<h2>Defanged IOC List</h2>
<div class="ioc-list">${nodes.map(n => defangAll(n.label)).join('<br/>')}</div>

<div class="footer">Generated by Fenrir | 0xprit3sh &nbsp;·&nbsp; graph-native threat intelligence</div>
</body>
</html>`

  // Open in new tab → user prints to PDF
  const win = window.open('', '_blank')
  if (!win) {
    // Fallback: download as HTML
    const blob = new Blob([html], { type: 'text/html' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `fenrir-report-${Date.now()}.html`
    a.click()
    return
  }
  win.document.write(html)
  win.document.close()
  setTimeout(() => win.print(), 800)
}